# Generated by Django 3.2.8 on 2021-10-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('nit_proveedor', models.IntegerField(blank=True, null=True, verbose_name='Nit proveedor')),
                ('precio_compra', models.IntegerField(blank=True, null=True, verbose_name='Precio compra')),
                ('precio_venta', models.IntegerField(blank=True, null=True, verbose_name='Precio venta')),
                ('tipoUnidad', models.IntegerField(blank=True, choices=[(1, 'Unidades'), (2, 'Paquetes'), (3, 'Mililitros'), (4, 'Gramos')], null=True, verbose_name='Tipo Unidad')),
                ('descripcion', models.TextField(blank=True, max_length=200, null=True, verbose_name='Descipcion')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
