# Generated by Django 3.2.9 on 2021-11-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('nit', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='Nit')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=100, verbose_name='Dierccion')),
                ('correo', models.CharField(blank=True, max_length=100, verbose_name='Correo')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Numero de contacto')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nit'],
            },
        ),
    ]
