# Generated by Django 3.2.9 on 2021-11-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='DNI')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=100, verbose_name='Apellido')),
                ('correo', models.CharField(blank=True, max_length=100, verbose_name='Correo')),
                ('edad', models.IntegerField(blank=True, null=True, verbose_name='Edad')),
                ('cargo', models.IntegerField(blank=True, choices=[(1, 'Administrador'), (2, 'Contador'), (3, 'Control de Inventarios'), (4, 'Servicio Tecnico')], null=True, verbose_name='Cargo')),
                ('contraseña', models.CharField(blank=True, max_length=100, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['nombre'],
            },
        ),
    ]
