# Generated by Django 3.2.8 on 2021-10-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.IntegerField(blank=True, choices=[(1, 'Administrador'), (2, 'Contador'), (3, 'Control de Inventarios'), (4, 'Servicio Tecnico')], null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.IntegerField(blank=True, null=True, verbose_name='DNI'),
        ),
    ]
