# Generated by Django 3.2.8 on 2021-10-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20211019_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.IntegerField(blank=True, choices=[(1, 'Administrador'), (2, 'Contador'), (3, 'Control de Inventarios'), (4, 'Servicio Tecnico')], null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
    ]
